### ISSUE TITLE
Add VirtualService for exposing DougTranslate

### ISSUE THREAD

**Issue by runyontr** [defenseunicorns/doug-translate#1]
Add a `DOMAIN` variable to match other packages so variables can be re-used.

Should be attached to the `istio-system/tenant` gateway

**Comment by justinthelaw** [comment]
Related to https://github.com/defenseunicorns/leapfrogai/tree/223-expose-lb-local

@CollectiveUnicorn's instructions: The command to expose docker is: `k3d cluster edit dubbd --port-add "8083:30535@loadbalancer"` or whatever port you want to use instead of 8083 all the connections are https so if you try to reach doug-translate from your browser you'll need to hit https://localhost:8083/
